### ISSUE TITLE
Should use 0 as padding？

### ISSUE THREAD

**Issue by liuxb-tofu** [logpai/deep-loglizer#2]
https://github.com/logpai/deep-loglizer/blob/ca50c2860bb0602d087a1109e5c27bfd5fc70477/deeploglizer/common/preprocess.py#L116
I see that the index value of ‘PADDING’ in word2Idx is 0, ‘OOV’ is 1, Shouldn't use 0 as the end padding here?

**Comment by JinYang88** [comment]
Thanks for pointing this out. 

In our setting, "PADDING" is 0 and "OOV" is 1 as shown in
https://github.com/logpai/deep-loglizer/blob/ca50c2860bb0602d087a1109e5c27bfd5fc70477/deeploglizer/common/preprocess.py#L43

For the following snippet, we use the `get` function of Dict to assign OOV the index 1, which is consistent with our setting.
https://github.com/logpai/deep-loglizer/blob/ca50c2860bb0602d087a1109e5c27bfd5fc70477/deeploglizer/common/preprocess.py#L116-L118

The `trp` function assigns PADDING tokens with index 1 is an error, and we've updated our code. Thanks again!
https://github.com/logpai/deep-loglizer/blob/ca50c2860bb0602d087a1109e5c27bfd5fc70477/deeploglizer/common/preprocess.py#L82
