### ISSUE TITLE
Error occurs when window_type is set to session

### ISSUE THREAD

**Issue by hirarinNakalab** [logpai/deep-loglizer#3]
https://github.com/logpai/deep-loglizer/blob/ca50c2860bb0602d087a1109e5c27bfd5fc70477/deeploglizer/common/dataloader.py#L62-L67

https://github.com/logpai/deep-loglizer/blob/ca50c2860bb0602d087a1109e5c27bfd5fc70477/deeploglizer/common/preprocess.py#L220-L222

Error in initializing log_dataset when window_type == "session" in FeatureExtractor. The solution I came up with is as follows.

```
elif self.window_type == "session":
    session_dict[session_id]["windows"] = [data_dict["templates"]]
    session_dict[session_id]["window_labels"] = [data_dict["label"]]
    session_dict[session_id]["window_anomalies"] = [data_dict["label"]]
```

**Comment by JinYang88** [comment]
Thanks for your attention for our project!

This is a new feature under development, and window_type should be set as default (i.e., sliding) for now.

**Comment by sometimestios** [comment]
So what's the meaning of window_anomalies?

```
sample = { 
     "session_idx": session_idx,  # not session id 
     "features": features[window_idx], 
     "window_labels": window_labels[window_idx], 
     "window_anomalies": window_anomalies[window_idx], 
 } 
```
