### ISSUE TITLE
Where are pre-trained weights?

### ISSUE THREAD

**Issue by thaondc** [logpai/deep-loglizer#7]
I’m writing with regard to your paper, "Experience Report: Deep Learning-based System Log Analysis for Anomaly Detection".  Recently, I have read it and I also referred to your public source code on github. But I had some problems. I can not run .py demo file in the [demo](https://github.com/logpai/deep-loglizer/tree/main/demo) folder . 
It might be there are no pre-trained weights on this source code. It would be great if you could help me to get it.

Best regards,
Thao Nguyen 
Ho Chi Minh University of Science

**Comment by zbchern** [comment]
Hi. You cannot run all .py demo files or just some of them? Most settings do not require pre-trained weights to run. Can you post more error info? Also, make sure the python version is correct. Thanks.

**Comment by thaondc** [comment]
Hi @zbchern,

I have run the .py demo file, I detect the problem that is the incorrect position of the .py demo file, it might be moved to the `deep-loglizer` folder. I have another problems. I can not get the results that you have presented in your paper. What are the parameters and data which you used to train the model?
Thank you.

**Comment by zbchern** [comment]
Hi @thaondc,

Good to know that you have fixed the issue. All the parameters we used are provided in the benchmarks folder. You may not get the results exactly the same as those in our paper, because we report the bests after multiple runs. However, you should be able to get comparable results. Thanks.
