### ISSUE TITLE
Custom log implementation

### ISSUE THREAD

**Issue by yanivweiss** [logpai/deep-loglizer#9]
Hi,

Thanks for the great work.

How can I use deep-log on a different type of log? 
Could you provide an example of a custom log implementation?

Thanks!

**Comment by zbchern** [comment]
Hi,

Technically yes.

The whole procedure to use deep-loglizer on a different type of log is similar: log parsing -> log partition and feature extraction -> anomaly detection.

Please refer to the data preprocess part to process your data, so they can be directly input to the models.
